{
    "identifier": "CVE-2019-20477",
    "summary": "CVE-2019-20477: PyYAML 5.1 through 5.1.2 has insufficient restrictions on the load and load_all functions because of a class deserialization issue, e.g., Popen is a class in the subprocess module. NOTE: this issue exists because of an incomplete fix for CVE-2017-18342.",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-38639"
        }
    ],
    "vulnerable_packages": [
        "pkg:pypi/pyyaml@5.1.2",
        "pkg:pypi/pyyaml@5.1.1",
        "pkg:pypi/pyyaml@5.1"
    ],
    "resolved_packages": [
        "pkg:pypi/pyyaml@5.1b3",
        "pkg:pypi/pyyaml@5.1b1",
        "pkg:pypi/pyyaml@4.2b1",
        "pkg:pypi/pyyaml@5.3b1",
        "pkg:pypi/pyyaml@3.02",
        "pkg:pypi/pyyaml@3.01",
        "pkg:pypi/pyyaml@5.2",
        "pkg:pypi/pyyaml@3.12",
        "pkg:pypi/pyyaml@3.06",
        "pkg:pypi/pyyaml@5.1b7",
        "pkg:pypi/pyyaml@5.3.1",
        "pkg:pypi/pyyaml@3.05",
        "pkg:pypi/pyyaml@4.2b2",
        "pkg:pypi/pyyaml@3.11",
        "pkg:pypi/pyyaml@4.2b4",
        "pkg:pypi/pyyaml@5.1b5",
        "pkg:pypi/pyyaml@5.2b1",
        "pkg:pypi/pyyaml@3.13rc1",
        "pkg:pypi/pyyaml@3.08",
        "pkg:pypi/pyyaml@3.07",
        "pkg:pypi/pyyaml@3.04",
        "pkg:pypi/pyyaml@3.10",
        "pkg:pypi/pyyaml@5.3",
        "pkg:pypi/pyyaml@3.13b1",
        "pkg:pypi/pyyaml@3.09",
        "pkg:pypi/pyyaml@3.13",
        "pkg:pypi/pyyaml@3.03"
    ]
}