{
    "identifier": "VULCODE-2020-09-26 12:51:22.046309",
    "summary": "python-pptx before 0.6.12 used a vulnerable version of Pillow.",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-36382"
        }
    ],
    "vulnerable_packages": [
        "pkg:pypi/python-pptx@0.6.5",
        "pkg:pypi/python-pptx@0.6.8",
        "pkg:pypi/python-pptx@0.5.4",
        "pkg:pypi/python-pptx@0.5.2",
        "pkg:pypi/python-pptx@0.5.7",
        "pkg:pypi/python-pptx@0.3.1",
        "pkg:pypi/python-pptx@0.6.4",
        "pkg:pypi/python-pptx@0.3.0",
        "pkg:pypi/python-pptx@0.2.5",
        "pkg:pypi/python-pptx@0.5.1",
        "pkg:pypi/python-pptx@0.6.3",
        "pkg:pypi/python-pptx@0.2.4",
        "pkg:pypi/python-pptx@0.5.3",
        "pkg:pypi/python-pptx@0.6.10",
        "pkg:pypi/python-pptx@0.2.3",
        "pkg:pypi/python-pptx@0.6.11",
        "pkg:pypi/python-pptx@0.4.2",
        "pkg:pypi/python-pptx@0.6.9",
        "pkg:pypi/python-pptx@0.2.6",
        "pkg:pypi/python-pptx@0.6.2",
        "pkg:pypi/python-pptx@0.2.1",
        "pkg:pypi/python-pptx@0.3.2",
        "pkg:pypi/python-pptx@0.4.0",
        "pkg:pypi/python-pptx@0.6.6",
        "pkg:pypi/python-pptx@0.5.5",
        "pkg:pypi/python-pptx@0.2.0",
        "pkg:pypi/python-pptx@0.3.0rc1",
        "pkg:pypi/python-pptx@0.5.0",
        "pkg:pypi/python-pptx@0.6.0",
        "pkg:pypi/python-pptx@0.5.8",
        "pkg:pypi/python-pptx@0.1.0a1",
        "pkg:pypi/python-pptx@0.6.7",
        "pkg:pypi/python-pptx@0.5.6",
        "pkg:pypi/python-pptx@0.4.1",
        "pkg:pypi/python-pptx@0.6.1",
        "pkg:pypi/python-pptx@0.2.2"
    ],
    "resolved_packages": [
        "pkg:pypi/python-pptx@0.6.13",
        "pkg:pypi/python-pptx@0.6.17",
        "pkg:pypi/python-pptx@0.6.18",
        "pkg:pypi/python-pptx@0.6.14",
        "pkg:pypi/python-pptx@0.6.16",
        "pkg:pypi/python-pptx@0.6.15",
        "pkg:pypi/python-pptx@0.6.12"
    ]
}