{
    "identifier": "VULCODE-2020-09-26 12:52:43.296693",
    "summary": "swauth before 1.1.0 has multiple undisclosed security vulnerabilities.",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-26150"
        }
    ],
    "vulnerable_packages": [
        "pkg:pypi/swauth@1.0.8"
    ],
    "resolved_packages": [
        "pkg:pypi/swauth@1.2.0",
        "pkg:pypi/swauth@1.1.0",
        "pkg:pypi/swauth@1.3.0"
    ]
}