{
    "identifier": "VULCODE-2020-09-26 12:51:02.646211",
    "summary": "pyorient before 1.4.9 has an SQL injection attack vector, exploitable in one location and potentially a few more, that allowed an attacker to change the WHERE clause in a query and cause it to return unexpected results",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-34150"
        }
    ],
    "vulnerable_packages": [
        "pkg:pypi/pyorient@1.4.7",
        "pkg:pypi/pyorient@1.4.6",
        "pkg:pypi/pyorient@1.4",
        "pkg:pypi/pyorient@1.4.5c",
        "pkg:pypi/pyorient@1.4.8",
        "pkg:pypi/pyorient@1.4.2a",
        "pkg:pypi/pyorient@1.3.1",
        "pkg:pypi/pyorient@1.4.6a0",
        "pkg:pypi/pyorient@1.4.3",
        "pkg:pypi/pyorient@1.4.4",
        "pkg:pypi/pyorient@1.3.0",
        "pkg:pypi/pyorient@1.2.4",
        "pkg:pypi/pyorient@1.4.2",
        "pkg:pypi/pyorient@1.4.1",
        "pkg:pypi/pyorient@1.0.0",
        "pkg:pypi/pyorient@1.2.5"
    ],
    "resolved_packages": [
        "pkg:pypi/pyorient@1.5",
        "pkg:pypi/pyorient@1.5.2",
        "pkg:pypi/pyorient@1.5.4",
        "pkg:pypi/pyorient@1.5.5",
        "pkg:pypi/pyorient@1.5.1",
        "pkg:pypi/pyorient@1.4.9"
    ]
}