{
    "identifier": "VULCODE-2020-09-26 12:44:05.225376",
    "summary": "Aethos 0.3.0.1 hotfixed NLTK package in setup.py and the vulnerable version.",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-37721"
        }
    ],
    "vulnerable_packages": [],
    "resolved_packages": [
        "pkg:pypi/aethos@2.0.1",
        "pkg:pypi/aethos@1.2.1",
        "pkg:pypi/aethos@1.2.5",
        "pkg:pypi/aethos@1.1.1",
        "pkg:pypi/aethos@2.0.0",
        "pkg:pypi/aethos@1.0.0",
        "pkg:pypi/aethos@1.2.3",
        "pkg:pypi/aethos@1.1.0",
        "pkg:pypi/aethos@1.1.2",
        "pkg:pypi/aethos@1.2.4",
        "pkg:pypi/aethos@1.2.0",
        "pkg:pypi/aethos@1.2.2",
        "pkg:pypi/aethos@1.0.1"
    ]
}