{
    "identifier": "VULCODE-2020-09-26 12:47:00.088018",
    "summary": "django-uni-form  0.9.0 fixes a XSS security issue. Errors cannot be rendered safe, because field's input can be part of the error message, that would mean XSS.",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-25796"
        }
    ],
    "vulnerable_packages": [
        "pkg:pypi/django-uni-form@0.8.0",
        "pkg:pypi/django-uni-form@0.5.1",
        "pkg:pypi/django-uni-form@0.8.0-beta",
        "pkg:pypi/django-uni-form@0.6.0",
        "pkg:pypi/django-uni-form@0.3",
        "pkg:pypi/django-uni-form@0.4b1",
        "pkg:pypi/django-uni-form@0.5.0",
        "pkg:pypi/django-uni-form@0.7.0"
    ],
    "resolved_packages": [
        "pkg:pypi/django-uni-form@0.9.0"
    ]
}