{
    "identifier": "VULCODE-2020-09-26 12:51:12.658684",
    "summary": "pytest-qt-app before 1.1.0  uses a subshell in workspace.run.",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-26062"
        }
    ],
    "vulnerable_packages": [
        "pkg:pypi/pytest-qt-app@1.0.1",
        "pkg:pypi/pytest-qt-app@1.0.0"
    ],
    "resolved_packages": []
}