{
    "identifier": "VULCODE-2020-09-26 12:48:35.297697",
    "summary": "Kedro-viz 3.0.0 includes a Snyk fix for one, unspecified vulnerability.",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-37615"
        }
    ],
    "vulnerable_packages": [
        "pkg:pypi/kedro-viz@2.0.0",
        "pkg:pypi/kedro-viz@2.1.1",
        "pkg:pypi/kedro-viz@2.1.0",
        "pkg:pypi/kedro-viz@1.0.1",
        "pkg:pypi/kedro-viz@1.0.2"
    ],
    "resolved_packages": [
        "pkg:pypi/kedro-viz@3.3.0",
        "pkg:pypi/kedro-viz@3.3.1",
        "pkg:pypi/kedro-viz@3.0.1",
        "pkg:pypi/kedro-viz@3.1.0",
        "pkg:pypi/kedro-viz@3.4.0",
        "pkg:pypi/kedro-viz@3.5.0",
        "pkg:pypi/kedro-viz@3.2.0",
        "pkg:pypi/kedro-viz@3.0.0",
        "pkg:pypi/kedro-viz@3.5.1"
    ]
}